package br.com.token;

public enum TokenType {
    IDENTIFICADOR,

    VERBO_CRIAR,
    VERBO_MOSTRAR,
    VERBO_ATRIBUIR,

    COMPARADOR_MENOR,
    COMPARADOR_MAIOR,
    COMPARADOR_IGUAL,
    COMPARADOR_MENOR_IGUAL,
    COMPARADOR_MAIOR_IGUAL,
    COMPARADOR_DIFERENTE,

    CONECTOR_A,
    CONECTOR_E,
    CONECTOR_OU,
    CONECTOR_COMO,
    CONECTOR_COM,
    CONECTOR_DE,

    VERBO_SOMAR,
    VERBO_DIVIDIR,
    VERBO_SUBTRAIR,
    VERBO_MULTIPLICAR,

    TIPO_NUMERICO,
    TIPO_TEXTO,
    TIPO_BOOLEANO,

    LITERAL_TEXTO,
    LITERAL_NUMERICO,
    LITERAL_BOOLEANO,

    PONTUACAO_PONTO_E_VIRGULA,
    PONTUACAO_PONTO,
    PONTUACAO_DOIS_PONTOS,
    PONTUACAO_PARENTESES,

    CONDICIONAL_SE,
    CONDICIONAL_SENAO,
    CONDICIONAL_ENTAO,

    DESCARTE
}